### ISSUE TITLE
add to docs

### ISSUE THREAD

**Issue by Prostak** [StoyanDimitrov/polivator#1]
Overall - very nice, saves me a lot of time and is a pleasure to use. Thank you!

1. The script checks "lightbox" conditions by hashing some area on the screen. This happens to be a part of the Inventory button (or may be the Build one - not sure). The button can blink by itself when there are new items inside. If it blinks, the lightbox check becomes unreliable, resulting in 10-20 sec delays or (usually) a complete stop. Not sure if this can be easily fixed, **but it is worth mentioning in the docs**, that the Inventory should be checked for new items before using the script. Probably. Nobody reads the docs but still, lol.

2. I have stable results with newly created Windows users, Google Chrome, screen resolution 2560 x 1440. Not so stable in my old account where I have played with Windows and Chrome settings, which may result in things misplaced. Probably the verified conditions may be mentioned also.

Again, thank you for this beauty.

**Comment by StoyanDimitrov** [comment]
Hey, nice to hear that this piece of code is useful!

I carefully choose the area to "sniff" for the lightboxing at start but the real one to blame is the Windows API. It turned out that the both versions of Windows I tested while developing (7 and 10) both returned different results. 1px off but still off. The other problem I faced is the lack of – to my knowledge – reliable way to make a screenshot of the "sniffed" area – for the exact same reason – to make it consistent across Windows API versions. So combining those both factors (at the tip of my head right now) I came across a pattern (have to dig in the code to freshen my memory) that worked for my 3 test environments but apparently leave out whole lot of others. Sorry about that. The obvious thing is to add a warning to the docs, as you suggest but this is not all that is easily breakable. The procedure is very machine performance dependent and probably DPI dependant.

Still it is very useful and at the time I wrote it there were no polished scripts like this.
