### ISSUE TITLE
Stuck at "Processing..."

### ISSUE THREAD

**Issue by edgeman16** [StoyanDimitrov/polivator#2]
I haven't been able to get this to function. It runs, clicks on the first tab of whatever setting I have enabled. Then dies.
If that tab was already active, then it clicks on the "go to start" button, but then seems to never finish after that.
Unfortunately I'm not sure what's going on more than that, there are no messages if I run it from the editor that indicate a problem that I can tell...

**Comment by StoyanDimitrov** [comment]
Well, that one used to work pretty nice... three years ago when game UI was in Flash. I guess in that time frame quite a few things had changed in the game. Not surprised it does not work.

**Comment by edgeman16** [comment]
Yeah, this is one of the fanciest AutoIT scripts I've ever seen, way more advanced than the static "click these X,Y spots 5 times, then this other spot, in a loop" that I had written awhile ago :)
The downside is I'm having a harder time debugging it because of how fancy it is.

**Comment by StoyanDimitrov** [comment]
It still boils down to this but because I make it independent from network latency and CPU processing power it must employ some waiting mechanism. According to your description it probably is slacking in one of the three `wait`s [here](https://github.com/StoyanDimitrov/polivator/blob/master/lib/social-bar.au3#L52).

The most easiest way to get feedback where it is waiting is to `ConsoleWrite` or by other means the first argument of [wait](https://github.com/StoyanDimitrov/polivator/blob/master/lib/wait.au3#L4). The reason of constant waiting is when the routine expects different colour or expects it on different place on the screen, or even both (different colour on different place).

As it was Flash based there were no other way around it but to track pixels of specified colour on specified screen coordinates. As one can expect this technique is __very__ fragile.

**Comment by edgeman16** [comment]
Okay so I finally got a chance to look at this again, and it's getting stuck in the "socialBarPageHasLoaded" function.
How did you determine the X and Y values for these two calls that are within that function?:
  Local Const $aid1 = getClientArea(264, -20, 97, 14)
  Local Const $aid2 = getClientArea(371, -20, 97, 14)
Are those X and Y relative to the bottom left corner of the window?

**Comment by StoyanDimitrov** [comment]
The function `getClientArea` is defined in `lib\area.au3` so yes first two arguments are the `x` and `y` coordinates (relative to the bottom left corner of the client area, because of the negative `y` here) of a rectangular area with 97x14px sides.

As to how to visualize given coordinates/areas on the screen there are GDIPlus functions to draw points/lines on the screen but it was a few pixels off so it is not precise enough to count on it.

Beware that the *relative* coordinates **are different** depending on the browser window being maximized or not! I don't think it is AutoIt to blame about, though.

**Comment by edgeman16** [comment]
No that makes sense, they are different buttons in different places.
In this case it's just testing if a certain colour exists within the entire box, so I think even being a few pixels off will be good enough. I'll have to look in to the GDIPlus functions to see if the box is misaligned now.
Out of curiosity, where you generally running this with maximized windows? I was doing it with a non-maximized window so I could see the status bar/scite console log.

**Comment by StoyanDimitrov** [comment]
Yes, maximized because that gave more or less the same results across different Windows API versions.

As far as I can remember GDI works with absolute coordinates of the screen as opposed to relative to the client area of the browser coordinates that I use in the script. In theory with maximized window they should overlap but in practice they don't and the problem is that the Windows API (or at least what AutoIt returns from it) takes in to account the borders around the browser window even in maximized state. To make the matter worst that border has different thickness in different Windows versions so it is not possible to make the script truly portable across Win versions while keeping the traversed screen areas smaller to the actual element on the screen. I guess compatibility with Win XP or 7 is not needed any more so your job is easier. If you see in the code "magic numbers" like `+/- 8` or ` +/- 12` they are used for just that.

Let's hope they fixed it in Win 10 and that's why the script is broken.
